home/urls.py
from django.urls import path
from . import views


urlpatterns= [

    path('', views.index, name='index'),


]

product/urls.py
from django.urls import path
from . import views





urlpatterns = [

    path('',views.index, name='product'),
    path('addcomment/<int:id>',views.addcomment,name='addcomment')

]

project_conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('hakkimizda/',views.hakkimizda, name='hakkimizda'),
    path('referanslar/',views.referanslar, name='referanslar'),
    path('iletisim/',views.iletisim, name='iletisim'),

    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products,name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    path('search/',views.product_search,name='product_search'),

]

#_______________ ADMIN'DE Image Görsellik..
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.forms import ModelForm,TextInput, Textarea


#_____________________ Site ayarları modeli__________
class MySetting(models.Model):
    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )

    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length = 255)
    company = models.CharField(max_length=150)
    address = models.TextField(blank = True,max_length=150)
    phone = models.CharField(blank = True,max_length=15)
    fax = models.CharField(blank = True,max_length = 15)
    email = models.CharField(blank = True,max_length = 75)
    smtp_server = models.CharField(blank = True,max_length=20)
    smtpemail = models.CharField(blank = True,max_length=20)
    smtppassword = models.CharField(blank = True,max_length = 10)
    smtpport = models.CharField(blank = True,max_length = 5)
    icon = models.ImageField(blank = True, upload_to='images/')
    facebook = models.CharField(blank = True,max_length =100)
    instagram = models.CharField(blank = True,max_length = 100)
    twitter = models.CharField(blank = True,max_length=100)
    aboutus = RichTextUploadingField(blank = True)
    contact = RichTextUploadingField(blank = True)
    references = RichTextUploadingField(blank = True)
    status = models.CharField(max_length=10,choices=STATUS, default=True)
    create_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.title



#________________________________ İLETİŞİM MODEL _______________________________
class ContactFormMessage(models.Model):
    STATUS = (
        ('New','Yeni'),
        ('Read','Okundu'),
        ('Closed','İşleme Konuldu'),
    )

    name = models.CharField(max_length=40)
    email = models.CharField(max_length=80)
    subject = models.CharField(blank=True,max_length=50)
    message = models.TextField(max_length=255)
    status = models.CharField(max_length=25, choices=STATUS, default='New')
    ip = models.CharField(blank=True,max_length=25)
    note = models.CharField(blank=True,max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)



    def __str__(self):
        return self.name

#________________________________ İLETİŞİM Form MODELİ _______________________________

class ContactFormu(ModelForm):

    class Meta:
        model = ContactFormMessage
        fields = ['name','email','subject','message']
        widgets = {
            'name' : TextInput(attrs={'class':'input','placeholder':'İsim & Soyisim'}),
            'subject' : TextInput(attrs={'class':'input','placeholder':'Konu'}),
            'email' : TextInput(attrs={'class':'input', 'placeholder':'Email Adresiniz'}),
            'message' : Textarea(attrs={'class':'input', 'placeholder':'Your Message','style':'height:30rem;'}),

        }

product/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm
from django.template.defaultfilters import slugify
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import  RichTextUploadingField

from mptt.models import MPTTModel, TreeForeignKey

#_________________________________ Category(models.Model)_________________________________________

class Category(MPTTModel):

    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True,upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(max_length=130,unique=True,editable=False)
    parent = TreeForeignKey('self',blank=True,null=True, related_name='children',on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add =True)
    update_at = models.DateField(auto_now=True)

    #Category -> Ağaç yapısı için
    class MPTTMeta:
       # level_attr ='mptt_level'
        order_insertion_by = ['title']




    #iç içe Kategori Gösterimi
    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent

        return ' / '.join(full_path[::-1])


    # Admin panelde Image gösterimi
    def my_image_tag(self):

        if self.image:
            return mark_safe(f'<img src="{self.image.url}" height="50"/>')
        else:
            return ""

    my_image_tag.short_description = 'Image'

    # slug'da ı'ları i yapma
    def get_unique_slug(self):
        slug = slugify(self.title.replace('ı', 'i'))
        unique_slug = slug
        counter = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, counter)
            counter += 1
        return unique_slug

    # slug'ı kaydetme
    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()

        return super(Category, self).save(*args, **kwargs)




#_________________________________ Product(models.Model)_________________________________________

class Product(models.Model):

    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail =RichTextUploadingField()
    slug = models.SlugField(max_length=130,unique =True,editable=False)
    status = models.CharField(max_length = 10,choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.title





    #Admin panelde Image gösterimi
    def image_tag(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" height="50"/>')
        else:
            return ""

    image_tag.short_description = 'Image'



    #slug'da ı'ları i yapma
    def get_unique_slug(self):
        slug = slugify(self.title.replace('ı', 'i'))
        unique_slug = slug
        counter = 1
        while Product.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, counter)
            counter += 1
        return unique_slug


    #slug'ı kaydetme
    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()

        return super(Product, self).save(*args, **kwargs)





#_________________________________ Images(models.Model)_________________________________________

class Images(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')



    def __str__(self):
        return self.title

    # Admin panelde Image gösterimi
    def my_image_tag(self):

        if self.image:
            return mark_safe(f'<img src="{self.image.url}" height="50"/>')
        else:
            return ""

    my_image_tag.short_description = 'Image'



#_________________________________ Comment(models.Model)_________________________________________

class Comment(models.Model):
    STATUS =(
        ('New','Yeni'),
        ('True','Evet'),
        ('False','Hayır'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length = 200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10,choices = STATUS,default='New')
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields=['subject','comment','rate']

home/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label='Search' ,max_length=100)

home/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

from home.forms import SearchForm
from home.models import MySetting, ContactFormMessage, ContactFormu
from product.models import Product, Category, Images, Comment


#__________________________________ index() _______________________________________
def index(request):

    setting = MySetting.objects.get()
    sliderdata = Product.objects.all()[:4] #Tüm Product'ları getirme, bana 4 tanesini getir.
    category = Category.objects.all()
    dayproducts = Product.objects.all()[:12] # Günün ürünleri
    lastproducts = Product.objects.all().order_by("-id")[:4] # Son ürünler
    randomproducts = Product.objects.all().order_by("?")[:4] # Rastgele ürünler




    context = {
        'setting':setting,
        'page':'home',
        'sliderdata':sliderdata,
        'category':category,
        'dayproducts':dayproducts,
        'lastproducts':lastproducts,
        'randomproducts':randomproducts,

    }

    return render(request,"index.html", context=context)


#__________________________________ hakkimizda() _______________________________________
def hakkimizda(request):
    setting = MySetting.objects.get()
    context = {
        'setting':setting,

    }

    return render(request,"hakkimizda.html", context)

#__________________________________ referanslar() _______________________________________
def referanslar(request):
    setting = MySetting.objects.get()
    context = {
        'setting':setting,

    }

    return render(request,"referanslar.html", context)


#__________________________________ iletisim() _______________________________________
def iletisim(request):

    if request.method=='POST':
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR') #Client ip alma
            data.save()
            messages.success(request,"Mesajınız başarılı bir şekilde gönderilmiştir. Teşekkür ederiz.")
            return HttpResponseRedirect('/iletisim')



    setting = MySetting.objects.get()
    form = ContactFormu()
    context = {
        'setting':setting,
        'form':form,
    }

    return render(request,"iletisim.html", context=context)

#__________________________________ category_products() _______________________________________
def category_products(request,id,slug):
        category = Category.objects.all()
        category_data =Category.objects.get(pk=id)
        products = Product.objects.filter(category_id = id)
        context = {
            'products':products,
            'category':category,
            'category_data':category_data,
        }

        return render(request,"products.html",context=context)

#__________________________________ product_detail() _______________________________________
def product_detail(request,id,slug):
    category = Category.objects.all()
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)
    #yorumları getirme
    comments = Comment.objects.filter(product_id=id,status='True')
    context = {
        'product':product,
        'category':category,
        'images':images,
        'comments':comments,
    }

    return render(request,"product_detail.html",context=context)


#__________________________________ product_search() _______________________________________

def product_search(request):
    if request.method=='POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query']#html içindeki name="query" kısmı
            products = Product.objects.filter(title__icontains=query)

            context = {
                'products':products,
                'category':category,
            }

            return render(request,"products_search.html",context=context)


        return HttpResponseRedirect('/')

product/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from product.models import CommentForm, Comment


def index(request):

    return HttpResponse("Hello There, Product page.")


@login_required(login_url='/login')
def addcomment(request,id):
        url = request.META.get('HTTP_REFERER')  # en son url'e dönüş yapmak için
        if request.method=='POST':
            form =CommentForm(request.POST)
            if form.is_valid():
                current_user = request.user

                data = Comment()
                data.user_id = current_user.id
                data.product_id = id
                data.subject = form.cleaned_data['subject'] #fields
                data.comment = form.cleaned_data['comment']
                data.rate = form.cleaned_data['rate']
                data.ip = request.META.get('REMOTE_ADDR')
                data.save()
                messages.success(request,"Yorumunuz başarıyla Gönderilmiştir. Teşekkür ederiz..")

                return HttpResponseRedirect(url)
        messages.warning(request,'Yorum Gönderilmedi')
        return HttpResponseRedirect(url)

home/templates/content.html
{% load static %}


	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section-title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Deals Of The Day</h2>
						<div class="pull-right">
							<div class="product-slick-dots-1 custom-dots"></div>
						</div>
					</div>
				</div>
				<!-- /section-title -->

            <!-- banner -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="banner banner-2">
						<img src="{% static './img/banner14.jpg' %}" alt="" >
						<div class="banner-caption">
							<h2 class="white-color">NEW<br>COLLECTION</h2>
							<button class="primary-btn">Shop Now</button>
						</div>
					</div>
				</div>
				<!-- /banner -->

				<div class="col-md-9 col-sm-6 col-xs-6">
					<div class="row">
						<div id="product-slick-1" class="product-slick">
						    {% for rs in dayproducts %}

							<div class="product product-single">
								<div class="product-thumb">
									<div class="product-label">
										<span>New</span>
										<span class="sale">-20%</span>
									</div>
									<ul class="product-countdown">
										<li><span>00 H</span></li>
										<li><span>00 M</span></li>
										<li><span>00 S</span></li>
									</ul>
									<a href="/product/{{ rs.id }}/{{ rs.slug }}" class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</a>
									<img src="{{ rs.image.url }}" alt=""  class="img-fluid">
								</div>
								<div class="product-body">
									<h3 class="product-price">${{ rs.price }}</h3>
									<div class="product-rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-o empty"></i>
									</div>
									<h2 class="product-name"><a href="#">{{ rs.title }}</a></h2>
									<div class="product-btns">
										<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
										<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
										<a href="/addtocard/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
									</div>
								</div>
							</div>

                            {% endfor %}

						</div>
					</div>
				</div>


            </div>
			<!-- /row -->

		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Latest Products</h2>
					</div>
				</div>
				<!-- section title -->

                {% for rs in lastproducts %}

				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<div class="product-thumb">
							<a href="/product/{{ rs.id }}/{{ rs.slug }}" class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</a>
							<img src="{{ rs.image.url }}" alt="" >
						</div>
						<div class="product-body">
							<h3 class="product-price">{{ rs.price }}</h3>
							<div class="product-rating">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i>
							</div>
							<h2 class="product-name"><a href="#">{{ rs.title }}</a></h2>
							<div class="product-btns">
								<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<a href="/addtocard/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
							</div>
						</div>
					</div>
				</div>

                {% endfor %}
			</div>
			<!-- /row -->


			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Picked For You</h2>
					</div>
				</div>

                {% for rs in randomproducts %}

				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<div class="product-thumb">
							<a href="/product/{{ rs.id }}/{{ rs.slug }}"  class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</a>
							<img src="{{ rs.image.url }}" alt="" >
						</div>
						<div class="product-body">
							<h3 class="product-price">${{ rs.price }}</h3>
							<div class="product-rating">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i>
							</div>
							<h2 class="product-name"><a href="#">{{ rs.title }}</a></h2>
							<div class="product-btns">
								<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<a href="/addtocard/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
							</div>
						</div>
					</div>
				</div>

				{% endfor %}

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

home/templates/hakkimizda.html
{% extends 'homebase.html' %}  <!-- homebase.html bağlı olarak çalışacağım.. -->
{% load static %}

{% block title %} Hakkımızda - {{ setting.company }}{% endblock title %}
{% block keywords %} {{ setting.keywords }}{% endblock %}
{% block description %} {{ setting.description }} {% endblock %}



{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />

{% endblock %}

{% block sidebar%}

    {% include 'sidebar.html' %}
{% endblock %}




{% block body %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'index' %}">Anasayfa</a></li>
				<li class="active"><a href="{% url 'hakkimizda' %}">Hakkımızda</a></li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
               {{ setting.aboutus|safe }}

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->



{% endblock %}

home/templates/index.html
{% extends 'homebase.html' %}  <!-- homebase.html bağlı olarak çalışacağım.. -->
{% load static %}
{% block title %} {{ setting.title }}{% endblock title %}
{% block keywords %} {{ setting.keywords }}{% endblock %}
{% block description %} {{ setting.description }} {% endblock %}



{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />

{% endblock %}

{% block sidebar%}

    {% include 'sidebar.html' %}
{% endblock %}



{% block slider %}
    {% include 'slider.html' %}
{% endblock %}


{% block body %}
    {% include 'content.html' %}
{% endblock %}

home/templates/product_detail.html
{% extends 'homebase.html' %}  <!-- homebase.html bağlı olarak çalışacağım.. -->
{% load static %}

{% block title %} {{ product.title }}{% endblock title %}
{% block keywords %} {{ product.keywords }}{% endblock %}
{% block description %} {{ product.description }} {% endblock %}



{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />

{% endblock %}

{% block sidebar%}

    {% include 'sidebar.html' %}
{% endblock %}




{% block body %}
<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="#">Home</a></li>
				<li><a href="#">Products</a></li>
				<li><a href="{% url 'category_products' product.category_id  product.category.slug %}">{{ product.category}}</a></li>
				<li class="active">{{ product.title }}</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->


	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!--  Product Details -->
				<div class="product product-details clearfix">
					<div class="col-md-6">
						<div id="product-main-view">
							<div class="product-view">
								<img src="{{ product.image.url }}" alt="">
							</div>
                            {% for rs in images %}
							<div class="product-view">
								<img src="{{ rs.image.url }}" alt="">
							</div>
                            {% endfor %}

						</div>
						<div id="product-view">
                            <div class="product-view">
								<img src="{{ product.image.url }}" alt="">
							</div>

                            {% for rs in images %}
							<div class="product-view">
								<img src="{{ rs.image.url }}" alt="">
							</div>
                            {% endfor %}


						</div>
					</div>
					<div class="col-md-6">
						<div class="product-body">
							<div class="product-label">
								<span>New</span>
								<span class="sale">-20%</span>
							</div>
							<h2 class="product-name">{{ product.title }}</h2>
							<h3 class="product-price">${{ product.price }}</h3>
							<div>
								<div class="product-rating">
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-o empty"></i>
								</div>
								<a href="#">3 Review(s) / Add Review</a>
							</div>
							<p><strong>Availability:</strong> In Stock <u> Mevcut Stock Adedi : {{ product.amount }}</u></p>
							<p><strong>Brand:</strong> E-SHOP</p>
							<p>{{ product.description }}</p>


							<div class="product-btns">
								<div class="qty-input">
									<span class="text-uppercase">Adet :</span>
									<input class="input" type="number" min="0" max="{{ product.amount }}" value="1">
								</div>
								<button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
								<div class="pull-right">
									<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
									<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
									<button class="main-btn icon-btn"><i class="fa fa-share-alt"></i></button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="product-tab">
							<ul class="tab-nav">
								<li class="active"><a data-toggle="tab" href="#tab1">Details</a></li>
								<li><a data-toggle="tab" href="#tab2">Reviews (3)</a></li>
							</ul>
							<div class="tab-content">
								<div id="tab1" class="tab-pane fade in active">
									<p>{{ product.detail|safe }}</p>
								</div>
								<div id="tab2" class="tab-pane fade in">

									<div class="row">
										<div class="col-md-6">
											<div class="product-reviews">

                                                    {% for comment in comments %}
                                                    <div class="single-review">
                                                        <div class="review-heading">
                                                            <div><a href="#"><i class="fa fa-user-o"></i> <b>{{ comment.user.first_name }}</b></a></div>
                                                            <div><a href="#"><i class="fa fa-clock-o"></i> {{ comment.create_at }}</a></div>
                                                            <div class="review-rating pull-right">

                                                                <i class="fa fa-star{% if comment.rate < 1 %}-o empty{% endif %}"></i>
                                                                <i class="fa fa-star{% if comment.rate < 2 %}-o empty{% endif %}"></i>
                                                                <i class="fa fa-star{% if comment.rate < 3 %}-o empty{% endif %}"></i>
                                                                <i class="fa fa-star{% if comment.rate < 4 %}-o empty{% endif %}"></i>
                                                                <i class="fa fa-star{% if comment.rate < 5 %}-o empty{% endif %}"></i>

                                                            </div>
                                                        </div>
                                                        <div class="review-body"> <strong>{{ comment.subject }}</strong>
                                                            <p>{{ comment.comment }}</p>
                                                        </div>
                                                    </div>

                                                    {% endfor %}



												<ul class="reviews-pages">
													<li class="active">1</li>
													<li><a href="#">2</a></li>
													<li><a href="#">3</a></li>
													<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
												</ul>
											</div>
										</div>
										<div class="col-md-6">
											<h4 class="text-uppercase">Write Your Review</h4>
											{% if messages %}

                                                {% for message in messages %}
                                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                                        {{ message }}
                                                    </div>

                                                {% endfor %}
                                            {% endif %}
											<form class="review-form" action="{% url 'addcomment'  product.id   %}" method="POST">
                                                {% csrf_token %}
												<div class="form-group">
													<input class="input" type="text" name='subject' id="id_subject"  placeholder="Subject" />
												</div>
												<div class="form-group">
													<textarea class="input" name="comment" id="id_comment" placeholder="Your Review"></textarea>
												</div>

												<div class="form-group">
													<div class="input-rating">
														<strong class="text-uppercase">Your Rating: </strong>
														<div class="stars">
															<input type="radio" id="star5" name="rate" value="5" /><label for="star5"></label>
															<input type="radio" id="star4" name="rate" value="4" /><label for="star4"></label>
															<input type="radio" id="star3" name="rate" value="3" /><label for="star3"></label>
															<input type="radio" id="star2" name="rate" value="2" /><label for="star2"></label>
															<input type="radio" id="star1" name="rate" value="1" /><label for="star1"></label>
														</div>
													</div>
												</div>

                                                {% if user.id is not  None %}

												<button class="primary-btn">Submit</button>
                                                {% else %}
                                                    Yorum eklemek için  <a href="/login"><i class="fa fa-user-o"></i><span style="font-size:1.8rem;font-weight: bolder"> Giriş</span></a> Yapınız...
                                                {% endif %}

											</form>

										</div>
									</div>



								</div>
							</div>
						</div>
					</div>

				</div>
				<!-- /Product Details -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


{% endblock %}

home/templates/referanslar.html
{% extends 'homebase.html' %}  <!-- homebase.html bağlı olarak çalışacağım.. -->
{% load static %}

{% block title %} Referanslarımız - {{ setting.company }}{% endblock title %}
{% block keywords %} {{ setting.keywords }}{% endblock %}
{% block description %} {{ setting.description }} {% endblock %}



{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />

{% endblock %}

{% block sidebar%}

    {% include 'sidebar.html' %}
{% endblock %}




{% block body %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'index' %}">Anasayfa</a></li>
				<li class="active"><a href="{% url 'referanslar' %}">Referanslarımız</a></li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
               {{ setting.references|safe }}

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->



{% endblock %}